# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb"}

modules = ["core.py"]

doc_url = "https://ylchan87.github.io/meter_reader/"

git_url = "https://github.com/ylchan87/meter_reader/tree/master/"

def custom_doc_links(name): return None
